name: cron
on:
  schedule:
    - cron: '* * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh job orchestration
        run: |
          curl --request POST \
          --url '${{ secrets.APP_BASE_URL }}/api/v1/refresh-jobs/orchestrations' \
          --header 'supabase-service-role-key: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}'