name: ESLint and Prettier Checks

on:
  - pull_request

jobs:
  lint-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: ESLint Check
        run: npm run lint
      - name: Prettier Check
        run: npm run prettier_check